# Generated by Django 5.0.6 on 2024-06-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=60)),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
