# Generated by Django 5.0.6 on 2024-06-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='currency_name',
            new_name='name',
        ),
    ]
