# Generated by Django 5.0.6 on 2024-06-30 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_currency_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='time',
            field=models.TimeField(default=datetime.time(16, 54, 5, 383349)),
        ),
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
