# Generated by Django 5.0.6 on 2024-07-01 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_currency_time_alter_currency_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currency',
            name='time',
            field=models.TimeField(default=datetime.time(7, 59, 53, 438128)),
        ),
    ]
